-- ============================================
-- TripEdge AI — Migration 004: Trip Replay
-- ============================================

-- Completed trip replays
create table public.trip_replays (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.profiles on delete cascade,
  itinerary_id uuid references public.itineraries on delete set null,
  active_trip_id uuid references public.active_trips on delete set null,
  group_trip_id uuid references public.group_trips on delete set null,

  -- Trip metadata
  city text not null,
  country text,
  dates_label text not null,               -- "Apr 17–21, 2026"
  num_days int not null,
  num_travelers int not null default 1,
  group_name text,

  -- Trip stats (aggregated at generation time)
  stats jsonb not null default '{}',       -- { steps, spots_visited, meals, photos_count, total_spent, per_person, saved_amount }

  -- AI-generated content
  theme text not null default 'editorial' check (theme in ('editorial', 'polaroid', 'minimal')),
  headline text not null,
  subheadline text,
  narrative text not null,
  pull_quote text,
  social_caption text,
  ai_model text not null default 'claude-sonnet-4-20250514',

  -- Highlights (structured)
  highlights jsonb not null default '[]',  -- [{ day, name, type, note }]

  -- Publishing
  is_public boolean not null default false,
  public_slug text unique,                 -- for shareable URL: tripedge.ai/replay/{slug}
  share_url text,
  view_count int not null default 0,
  share_count int not null default 0,

  -- Timestamps
  generated_at timestamptz not null default now(),
  last_viewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_replays_user on public.trip_replays (user_id, created_at desc);
create unique index idx_replays_slug on public.trip_replays (public_slug) where public_slug is not null;

-- Photos associated with a replay
create table public.replay_photos (
  id uuid primary key default uuid_generate_v4(),
  replay_id uuid not null references public.trip_replays on delete cascade,
  user_id uuid not null references public.profiles on delete cascade,
  storage_path text not null,              -- Supabase Storage path
  public_url text not null,
  thumbnail_url text,
  caption text,
  day_number int,
  sort_order int not null default 0,
  width int,
  height int,
  exif_data jsonb,                         -- { lat, lng, taken_at, camera }
  is_hero boolean not null default false,  -- used as the main cover image
  is_featured boolean not null default false,
  uploaded_at timestamptz not null default now()
);

create index idx_replay_photos on public.replay_photos (replay_id, sort_order);
create index idx_replay_photos_day on public.replay_photos (replay_id, day_number);

-- User-uploaded photos (pre-replay, bulk upload)
create table public.trip_photo_uploads (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.profiles on delete cascade,
  active_trip_id uuid references public.active_trips on delete set null,
  storage_path text not null,
  public_url text not null,
  filename text,
  size_bytes bigint,
  mime_type text,
  width int,
  height int,
  exif_lat numeric(10,7),
  exif_lng numeric(10,7),
  exif_taken_at timestamptz,
  ai_caption text,                         -- auto-generated by vision model
  ai_location_guess text,                  -- AI-inferred location name
  ai_category text,                        -- food, landmark, people, scenery, etc.
  is_selected_for_replay boolean not null default false,
  uploaded_at timestamptz not null default now()
);

create index idx_photo_uploads_user on public.trip_photo_uploads (user_id, uploaded_at desc);
create index idx_photo_uploads_trip on public.trip_photo_uploads (active_trip_id);

-- Share events (analytics)
create table public.replay_share_events (
  id uuid primary key default uuid_generate_v4(),
  replay_id uuid not null references public.trip_replays on delete cascade,
  platform text not null check (platform in ('instagram', 'tiktok', 'twitter', 'facebook', 'whatsapp', 'link', 'download', 'pdf')),
  shared_at timestamptz not null default now()
);

create index idx_share_events_replay on public.replay_share_events (replay_id, shared_at desc);

-- View events (for public replays)
create table public.replay_view_events (
  id uuid primary key default uuid_generate_v4(),
  replay_id uuid not null references public.trip_replays on delete cascade,
  viewer_ip_hash text,                     -- hashed for privacy
  referrer text,
  viewed_at timestamptz not null default now()
);

create index idx_view_events_replay on public.replay_view_events (replay_id, viewed_at desc);

-- ─── Generate public slug function ───
create or replace function public.generate_replay_slug()
returns trigger as $$
begin
  if new.is_public = true and new.public_slug is null then
    new.public_slug := lower(
      regexp_replace(new.city, '[^a-zA-Z0-9]', '', 'g')
    ) || '-' || encode(gen_random_bytes(4), 'hex');
    new.share_url := 'https://tripedge.ai/replay/' || new.public_slug;
  end if;
  return new;
end;
$$ language plpgsql;

create trigger set_replay_slug
  before insert or update on public.trip_replays
  for each row execute function public.generate_replay_slug();

-- ─── Increment view count function ───
create or replace function public.increment_replay_views(p_slug text)
returns void as $$
begin
  update public.trip_replays
  set view_count = view_count + 1,
      last_viewed_at = now()
  where public_slug = p_slug;
end;
$$ language plpgsql security definer;

-- ─── RLS ───
alter table public.trip_replays enable row level security;
alter table public.replay_photos enable row level security;
alter table public.trip_photo_uploads enable row level security;
alter table public.replay_share_events enable row level security;
alter table public.replay_view_events enable row level security;

-- Owner manages their own replays
create policy "own_replays" on public.trip_replays for all using (auth.uid() = user_id);
-- Public replays viewable by anyone
create policy "public_replays" on public.trip_replays for select using (is_public = true);

create policy "own_replay_photos" on public.replay_photos for all using (auth.uid() = user_id);
-- Photos in public replays are viewable
create policy "public_replay_photos" on public.replay_photos for select using (
  exists (select 1 from public.trip_replays where id = replay_id and is_public = true)
);

create policy "own_uploads" on public.trip_photo_uploads for all using (auth.uid() = user_id);
create policy "own_share_events" on public.replay_share_events for all using (
  exists (select 1 from public.trip_replays where id = replay_id and user_id = auth.uid())
);
-- View events insertable by anyone (for public replays)
create policy "insert_view_events" on public.replay_view_events for insert with check (
  exists (select 1 from public.trip_replays where id = replay_id and is_public = true)
);

-- ─── Storage bucket for trip photos ───
-- Run in Supabase dashboard or via API:
-- insert into storage.buckets (id, name, public) values ('trip-photos', 'trip-photos', true);
